# Importing libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# Loading Dataset

In [2]:
hr_data=pd.read_csv(r"C:\Users\Mihir\Desktop\DATASETS\HR ANALYTICS.csv",index_col=0)

In [3]:
hr_data.head()

department     region         education gender  \
employee_id                                                          
65438        Sales & Marketing   region_7  Master's & above      f   
65141               Operations  region_22        Bachelor's      m   
7513         Sales & Marketing  region_19        Bachelor's      m   
2542         Sales & Marketing  region_23        Bachelor's      m   
48945               Technology  region_26        Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [4]:
hr_data.shape

(54808, 13)

# Handling Missing Values

In [5]:
hr_data.isnull().sum()

department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [6]:
hr_data=hr_data.dropna()

In [7]:
hr_data.isnull().sum()

department              0
region                  0
education               0
gender                  0
recruitment_channel     0
no_of_trainings         0
age                     0
previous_year_rating    0
length_of_service       0
KPIs_met >80%           0
awards_won?             0
avg_training_score      0
is_promoted             0
dtype: int64

In [8]:
hr_data.shape

(48660, 13)

In [9]:
hr_df=pd.DataFrame.copy(hr_data)

In [10]:
hr_df.head()

department     region         education gender  \
employee_id                                                          
65438        Sales & Marketing   region_7  Master's & above      f   
65141               Operations  region_22        Bachelor's      m   
7513         Sales & Marketing  region_19        Bachelor's      m   
2542         Sales & Marketing  region_23        Bachelor's      m   
48945               Technology  region_26        Bachelor's      m   

            recruitment_channel  no_of_trainings  age  previous_year_rating  \
employee_id                                                                   
65438                  sourcing                1   35                   5.0   
65141                     other                1   30                   5.0   
7513                   sourcing                1   34                   3.0   
2542                      other                2   39                   1.0   
48945                     other                1   45                   3.0   

             length_of_service  KPIs_met >80%  awards_won?  \
employee_id                                                  
65438                        8              1            0   
65141                        4              0            0   
7513                         7              0            0   
2542                        10              0            0   
48945                        2              0            0   

             avg_training_score  is_promoted  
employee_id                                   
65438                        49            0  
65141                        60            0  
7513                         50            0  
2542                         50            0  
48945                        73            0

In [11]:
hr_df.dtypes

department               object
region                   object
education                object
gender                   object
recruitment_channel      object
no_of_trainings           int64
age                       int64
previous_year_rating    float64
length_of_service         int64
KPIs_met >80%             int64
awards_won?               int64
avg_training_score        int64
is_promoted               int64
dtype: object

# Converting Categorical to Numerical

In [12]:
colname=[]
for x in hr_df.columns:
    if hr_df[x].dtype=='object':
        colname.append(x)
colname

['department', 'region', 'education', 'gender', 'recruitment_channel']

In [13]:
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in colname:
    hr_df[x]=le.fit_transform(hr_df[x])

In [14]:
hr_df.head()

department  region  education  gender  recruitment_channel  \
employee_id                                                               
65438                 7      31          2       0                    2   
65141                 4      14          0       1                    0   
7513                  7      10          0       1                    2   
2542                  7      15          0       1                    0   
48945                 8      18          0       1                    0   

             no_of_trainings  age  previous_year_rating  length_of_service  \
employee_id                                                                  
65438                      1   35                   5.0                  8   
65141                      1   30                   5.0                  4   
7513                       1   34                   3.0                  7   
2542                       2   39                   1.0                 10   
48945                      1   45                   3.0                  2   

             KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
employee_id                                                               
65438                    1            0                  49            0  
65141                    0            0                  60            0  
7513                     0            0                  50            0  
2542                     0            0                  50            0  
48945                    0            0                  73            0

In [15]:
#seperate dependent and independent variables

X=hr_df.values[:,:-1]
Y=hr_df.values[:,-1]

# scaling the data

In [16]:
from sklearn.preprocessing import StandardScaler

scalar=StandardScaler()

scalar.fit(X)   #FIT WILL TRAIN THE SCALAR OBJECT AND DECIDE UPN NEW RANGES TO BE APPLIED,

X=scalar.transform(X) 
#TRANSFORM WILL SEEK THE RANGES FROM THE SCALAR OBJECT WHICH WAS LEARNT,AND TRANSFORM THE ORIGINAL VALUES WITH SCALED VALUES.

print(X)

#x has now changed into float datatype.we need to convert y too into integer.

[[ 0.81953619  1.76864504  1.50436696 ...  1.34359879 -0.15391006
  -1.10019636]
 [-0.38798019 -0.15845292 -0.67214112 ... -0.7442698  -0.15391006
  -0.2714691 ]
 [ 0.81953619 -0.61188773 -0.67214112 ... -0.7442698  -0.15391006
  -1.02485752]
 ...
 [-0.38798019  0.4083406   1.50436696 ... -0.7442698  -0.15391006
  -0.57282447]
 [-1.99800204 -1.74547477 -0.67214112 ...  1.34359879 -0.15391006
   1.15996889]
 [-1.19299112 -0.15845292 -0.67214112 ... -0.7442698  -0.15391006
  -1.10019636]]


In [17]:
#CONVERTING Y INTO int Datatype.

Y=Y.astype(int)

# train-test split

In [18]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

# Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

logistic_classifier=LogisticRegression(random_state=42)
logistic_classifier.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=42, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

# Model Prediction

In [20]:
y_pred=logistic_classifier.predict(X_test)

# Model Evaluation

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred)
print("CONFUSION MATRIX: ")
print(cfm)

print('Classification Report: ')

print(classification_report(Y_test,y_pred))

acc=accuracy_score(Y_test,y_pred)
print("Accuracy of the model: ",acc)


CONFUSION MATRIX: 
[[13233    46]
 [ 1220    99]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.95     13279
           1       0.68      0.08      0.14      1319

    accuracy                           0.91     14598
   macro avg       0.80      0.54      0.54     14598
weighted avg       0.89      0.91      0.88     14598

Accuracy of the model:  0.9132757912042746


# Model Tuning

In [22]:
y_pred_prob=logistic_classifier.predict_proba(X_test)
print(y_pred_prob)

[[0.92675959 0.07324041]
 [0.88242378 0.11757622]
 [0.97691162 0.02308838]
 ...
 [0.91542338 0.08457662]
 [0.90483356 0.09516644]
 [0.97426765 0.02573235]]


In [23]:
#appending the values in probability matrix to 0 and 1
y_pred_logistic=[]
for value in y_pred_prob[:,1]:
    if value > 0.46:
        y_pred_logistic.append(1)
    else:
        y_pred_logistic.append(0)
print(y_pred_logistic)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [24]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred_logistic)
print("CONFUSION MATRIX: ")
print(cfm)

print('Classification Report: ')

print(classification_report(Y_test,y_pred_logistic))

acc=accuracy_score(Y_test,y_pred_logistic)
print("Accuracy of the model: ",acc)
acc_logistic=acc.round(4)

CONFUSION MATRIX: 
[[13223    56]
 [ 1204   115]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.95     13279
           1       0.67      0.09      0.15      1319

    accuracy                           0.91     14598
   macro avg       0.79      0.54      0.55     14598
weighted avg       0.89      0.91      0.88     14598

Accuracy of the model:  0.9136868064118372


# Support Vector Machines (SVM)

In [40]:
from sklearn.svm import SVC
model=SVC(random_state=42)

model.fit(X_train,Y_train)

y_pred_svm=model.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred_svm)
print("CONFUSION MATRIX: ")
print(cfm)

print('Classification Report: ')

print(classification_report(Y_test,y_pred_svm))

acc=accuracy_score(Y_test,y_pred_svm)
print("Accuracy of the model: ",acc)

acc_svm=acc.round(4)

CONFUSION MATRIX: 
[[13254    25]
 [ 1189   130]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96     13279
           1       0.84      0.10      0.18      1319

    accuracy                           0.92     14598
   macro avg       0.88      0.55      0.57     14598
weighted avg       0.91      0.92      0.89     14598

Accuracy of the model:  0.9168379230031511


# KNN

In [44]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))), 
                               metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,y_pred)))

[(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (1, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (1, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred)
print("CONFUSION MATRIX: ")
print(cfm)

print('Classification Report: ')

print(classification_report(Y_test,y_pred))

acc=accuracy_score(Y_test,y_pred)
print("Accuracy of the model: ",acc)

CONFUSION MATRIX: 
[[13265    14]
 [ 1227    92]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96     13279
           1       0.87      0.07      0.13      1319

    accuracy                           0.91     14598
   macro avg       0.89      0.53      0.54     14598
weighted avg       0.91      0.91      0.88     14598

Accuracy of the model:  0.9149883545691191


# Model Tuning

In [46]:
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,31):
    model_KNN = KNeighborsClassifier(K,metric="euclidean")
    model_KNN.fit(X_train, Y_train) 
    y_pred_knn= model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,y_pred_knn), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,y_pred_knn)


Accuracy is  0.882312645567886 for K-Value: 1
Accuracy is  0.910330182216742 for K-Value: 2
Accuracy is  0.9029319084806138 for K-Value: 3
Accuracy is  0.9123167557199616 for K-Value: 4
Accuracy is  0.9088231264556789 for K-Value: 5
Accuracy is  0.9140293190848061 for K-Value: 6
Accuracy is  0.9127277709275243 for K-Value: 7
Accuracy is  0.9149883545691191 for K-Value: 8
Accuracy is  0.914714344430744 for K-Value: 9
Accuracy is  0.9149883545691191 for K-Value: 10
Accuracy is  0.9147828469653377 for K-Value: 11
Accuracy is  0.9149198520345253 for K-Value: 12
Accuracy is  0.9145773393615564 for K-Value: 13
Accuracy is  0.9149883545691191 for K-Value: 14
Accuracy is  0.9147828469653377 for K-Value: 15
Accuracy is  0.9145773393615564 for K-Value: 16
Accuracy is  0.914714344430744 for K-Value: 17
Accuracy is  0.9147828469653377 for K-Value: 18
Accuracy is  0.9151253596383067 for K-Value: 19
Accuracy is  0.9152623647074942 for K-Value: 20
Accuracy is  0.9147828469653377 for K-Value: 21
Accur

In [47]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):  #comparing current value of k with max value in dictionary
        print(k,":",my_dict[k])


20 : 0.9152623647074942


In [48]:
#predicting using the KNeighbors_Classifier
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=20,metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

y_pred_knn=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred_knn)
print("CONFUSION MATRIX: ")
print(cfm)

print('Classification Report: ')

print(classification_report(Y_test,y_pred_knn))

acc=accuracy_score(Y_test,y_pred_knn)
print("Accuracy of the model: ",acc)
acc_knn=acc.round(4)

CONFUSION MATRIX: 
[[13255    24]
 [ 1213   106]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.92      1.00      0.96     13279
           1       0.82      0.08      0.15      1319

    accuracy                           0.92     14598
   macro avg       0.87      0.54      0.55     14598
weighted avg       0.91      0.92      0.88     14598

Accuracy of the model:  0.9152623647074942


# Decision Trees

In [50]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion="gini",random_state=42)

dtree.fit(X_train,Y_train)

#predict the model

y_pred=dtree.predict(X_test)

In [51]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred)
print("CONFUSION MATRIX: ")
print(cfm)

print('Classification Report: ')

print(classification_report(Y_test,y_pred))

acc=accuracy_score(Y_test,y_pred)
print("Accuracy of the model: ",acc)
#acc_dt=acc.round(4)

CONFUSION MATRIX: 
[[12442   837]
 [  769   550]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.94      0.94      0.94     13279
           1       0.40      0.42      0.41      1319

    accuracy                           0.89     14598
   macro avg       0.67      0.68      0.67     14598
weighted avg       0.89      0.89      0.89     14598

Accuracy of the model:  0.8899849294423894


# Model Tuning

In [57]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion="entropy",max_depth=10,min_samples_leaf=5,random_state=42)

dtree.fit(X_train,Y_train)

#predict the model

y_pred_dt=dtree.predict(X_test)

In [58]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(Y_test,y_pred_dt)
print("CONFUSION MATRIX: ")
print(cfm)

print('Classification Report: ')

print(classification_report(Y_test,y_pred_dt))

acc=accuracy_score(Y_test,y_pred_dt)
print("Accuracy of the model: ",acc)
acc_dt=acc.round(4)

CONFUSION MATRIX: 
[[13217    62]
 [  938   381]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.93      1.00      0.96     13279
           1       0.86      0.29      0.43      1319

    accuracy                           0.93     14598
   macro avg       0.90      0.64      0.70     14598
weighted avg       0.93      0.93      0.92     14598

Accuracy of the model:  0.93149746540622


# Creating Final Results

In [59]:
raw_datadf = {'Model Name': ['Logistic Regrerssion','Support Vector Machines(SVM)','K-Nearest Neighbor','Decision Trees'],
            'Accuracy':[acc_logistic,acc_svm,acc_knn,acc_dt]}

In [60]:
model_df=pd.DataFrame(data=raw_datadf)

In [61]:
model_df

Model Name  Accuracy
0          Logistic Regrerssion    0.9137
1  Support Vector Machines(SVM)    0.9168
2            K-Nearest Neighbor    0.9153
3                Decision Trees    0.9315